sudo: false

language: perl6

perl6:
  - latest

branches:
  only:
    - master

install:
  - rakudobrew build zef

before_script:
  - zef --/test --/test-depends install Digest;
  - zef --/test --/test-depends install Digest::HMAC;
  - zef --/test --/test-depends install URI;


